version: "3"
services:
    mysql:
        container_name: mysql
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
            resources:
                limits:
                    memory: 512M
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=semive
        image: mysql:5.6
        networks:
            main:
                aliases:
                    - mysql
        ports:
            - 3306:3306
        restart: always

    semive-backend:
        build: .
        container_name: semive-backend
        depends_on:
            - mysql
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
            resources:
                limits:
                    memory: 1024M
        environment:
            - SEMIVE_DATABASE_URL=mysql
        image: mahenrique94/semive-backend
        networks:
            main:
                aliases:
                    - semive-backend
        ports:
            - 9090:9090
        restart: always

networks:
    main: