server:
  servlet:
    context-path: /semive/api

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/semive
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver